language: node_js
node_js:
  - "node"

branches:
  only:
  - dev
script:
- npm run build
deploy:
    provider: pages
    github_token: $GH_TOKEN
    local_dir: dist
    target_branch: master
    skip_cleanup: true
    keep_history: true
    verbose: true
    on:
        branch: dev