language: node_js
node_js:
- 16
branches:
  only:
  - dev
script:
- yarn build
deploy:
  provider: pages
  token: "$GH_TOKEN"
  local_dir: dist
  target_branch: master
  strategy: git
  skip_cleanup: true
  keep_history: true
  on:
    branch: dev
